"""empty message

Revision ID: 235d4f938b09
Revises: 3f4e7ad016da
Create Date: 2020-03-18 21:08:22.606934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235d4f938b09'
down_revision = '3f4e7ad016da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sliders_home', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sliders_home', 'active')
    # ### end Alembic commands ###
